### ISSUE TITLE
Su Raspberry 4, installando lo script per la Breakout si interrompe l'audio dal jack 3.5

### ISSUE THREAD

**Issue by fdambrosio1981** [vince87/JammaBreakout#1]
Ciao Vincenzo,
ho recuperato una Raspberry pi 4 sulla quale ho montato la tua Jamma Breakout (quella con i comandi e l'audio). Appena installo lo script però non c'è più modo di far uscire l'audio dal jack 3.5 della Raspberry. I comandi funzionano invece correttamente. Disattivando la breakout e riavviando il sistema, l'audio torna (anche se con molto rumore di fondo), ma non funzionano più ovviamente i comandi.
So che la breakout ha le uscite audio per i canali L e R sulla board e in caso si possono usare quelli, ma il jack 3.5 era molto comodo.
Un saluto

**Comment by vince87** [comment]
Ciao, puoi installare solo la parte joystick:

cloni questo progetto, entri nella cartella e lanci questi comandi:

	sudo mkdir /usr/src/mk_arcade_joystick_rpi-0.1.5/
	sudo cp -a * /usr/src/mk_arcade_joystick_rpi-0.1.5/
	sudo dkms build -m mk_arcade_joystick_rpi -v 0.1.5
	sudo dkms install -m mk_arcade_joystick_rpi -v 0.1.5
	sudo modprobe mk_arcade_joystick_rpi map=1,2
	sudo rm /etc/modprobe.d/mk_arcade_joystick_rpi.conf
	echo "options mk_arcade_joystick_rpi map=1,2" >> mk_arcade_joystick_rpi.conf
	sudo mv mk_arcade_joystick_rpi.conf /etc/modprobe.d/
	sudo grep 'mk_arcade_joystick_rpi' /etc/modules > /dev/null 2>&1
	sudo sh -c "echo 'mk_arcade_joystick_rpi' >> /etc/modules"

uno alla volta

**Comment by fdambrosio1981** [comment]
Ok grazie!

Ho però errore nell'esecuzione del terzo comando:

pi@retropie:~/JammaBreakout $ sudo dkms build -m mk_arcade_joystick_rpi -v 0.1.5
Error! Could not locate dkms.conf file.
File: /usr/src/mk_arcade_joystick_rpi-0.1.5/dkms.conf does not exist.

Il file dkms.conf si trova invece nel path /usr/src/mk_arcade_joystick_rpi-0.1.5/mk_arcade_joystick/dkms.conf

**Comment by vince87** [comment]
si, c'è un errore...
prima del secondo comando entra nella cartella mk_arcade_joystick

**Comment by fdambrosio1981** [comment]
ok grazie si me ne ero accorto. Ti ringrazio molto, ora funzionano sia i comandi che l'audio dal jack cuffie!
